name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '25'
      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean shadowJar
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: plugin-jars
          path: build/libs/*.jar